name: Testing

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "5 1 * * *"

jobs:
  testing:
    name: Test- and linting
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run go fmt
        if: runner.os != 'Windows'
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: Run go vet
        run: make vet

      - name: Run staticcheck
        run: make staticcheck

  compile:
    name: Compile application
    runs-on: ubuntu-22.04
    needs: [testing]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Build
        run: make build

  # Right now we don't build the Docker image.
  # Compiling the application might be ok enough for now.
